//! Tool registry. Each group lives in its own module and exposes `fn tools() -> Vec<Tool>`; adding a group
//! means adding a module and one line in `Registry::new` (keeps parallel work conflict-free).

mod common;
mod doc;
mod features;
mod output;
mod params;
mod sketch;

use qymcad_engine::Session;
use schemars::JsonSchema;
use serde::de::DeserializeOwned;
use serde_json::{json, Value};

/// MCP content items (`[{ "type": "text", "text": ... }, { "type": "image", ... }]`).
pub type Content = Vec<Value>;

/// Server state shared by all tools: the one open document.
#[derive(Default)]
pub struct State {
    pub session: Option<Session>,
}

impl State {
    pub fn doc(&mut self) -> Result<&mut Session, String> {
        self.session.as_mut().ok_or_else(|| "no document is open: call doc_new or doc_open first".to_string())
    }
}

type Handler = Box<dyn Fn(&mut State, Value) -> Result<Content, String>>;

pub struct Tool {
    pub name: &'static str,
    pub description: &'static str,
    pub schema: Value,
    handler: Handler,
}

/// A tool whose result is a JSON value, returned to the model as compact JSON text.
pub fn tool<A, F>(name: &'static str, description: &'static str, f: F) -> Tool
where
    A: DeserializeOwned + JsonSchema,
    F: Fn(&mut State, A) -> Result<Value, String> + 'static,
{
    tool_content(name, description, move |st, a: A| f(st, a).map(|v| vec![json!({ "type": "text", "text": v.to_string() })]))
}

/// A tool that builds its own content items (e.g. images).
pub fn tool_content<A, F>(name: &'static str, description: &'static str, f: F) -> Tool
where
    A: DeserializeOwned + JsonSchema,
    F: Fn(&mut State, A) -> Result<Content, String> + 'static,
{
    let handler: Handler = Box::new(move |st, args| {
        let a: A = serde_json::from_value(args).map_err(|e| format!("bad arguments for `{name}`: {e}"))?;
        f(st, a)
    });
    Tool { name, description, schema: input_schema::<A>(), handler }
}

/// The JSON schema of an argument struct, trimmed to what MCP clients need.
fn input_schema<A: JsonSchema>() -> Value {
    let mut v = serde_json::to_value(schemars::schema_for!(A)).unwrap_or_else(|_| json!({}));
    if let Some(o) = v.as_object_mut() {
        o.remove("$schema");
        o.remove("title");
        o.entry("type").or_insert(json!("object"));
    }
    v
}

pub struct Registry {
    tools: Vec<Tool>,
    state: State,
}

impl Default for Registry {
    fn default() -> Self {
        Self::new()
    }
}

impl Registry {
    pub fn new() -> Registry {
        let mut tools = Vec::new();
        tools.extend(doc::tools());
        tools.extend(params::tools());
        tools.extend(sketch::tools());
        tools.extend(features::tools());
        tools.extend(output::tools());
        Registry { tools, state: State::default() }
    }

    pub fn list(&self) -> Vec<Value> {
        self.tools.iter().map(|t| json!({ "name": t.name, "description": t.description, "inputSchema": t.schema })).collect()
    }

    /// `Err` = no such tool (a protocol error). `Ok(Err)` = the tool ran and failed (a tool error for the model).
    pub fn call(&mut self, name: &str, args: Value) -> Result<Result<Content, String>, String> {
        let t = self.tools.iter().find(|t| t.name == name).ok_or_else(|| format!("unknown tool: {name}"))?;
        Ok((t.handler)(&mut self.state, args))
    }

    /// docs/TOOLS.md, generated from the registry so it cannot drift.
    pub fn markdown(&self) -> String {
        let mut s =
            String::from("# Tools\n\nGenerated by `cargo run -p qymcad-mcp -- --dump-tools > docs/TOOLS.md`. Do not edit by hand.\n\n");
        for t in &self.tools {
            s.push_str(&format!("- [`{}`](#{})\n", t.name, t.name));
        }
        for t in &self.tools {
            let schema = serde_json::to_string_pretty(&t.schema).unwrap_or_default();
            s.push_str(&format!("\n## {}\n\n{}\n\n```json\n{}\n```\n", t.name, t.description, schema));
        }
        s
    }
}
